[project]
name = "demo-edu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "monsterui>=1.0.10",
    "requests>=2.32.3",
]
